export enum CandidateStatus {
  NEW = 'NEW',
  SUBMITTED = 'SUBMITTED',
  SCREENING = 'SCREENING',
  SCREEN_SELECTED = 'SCREEN_SELECTED',
  SCREEN_REJECTED = 'SCREEN_REJECTED',

  TECH = 'TECH',
  TECH_SELECTED = 'TECH_SELECTED',
  TECH_REJECTED = 'TECH_REJECTED',
  OPS = 'OPS',
  OPS_SELECTED = 'OPS_SELECTED',
  OPS_REJECTED = 'OPS_REJECTED',

  IDENTIFIED = 'IDENTIFIED',
  YET_TO_JOIN = 'YET_TO_JOIN',
  SELECTED = 'SELECTED',
  REJECTED = 'REJECTED',
  ONBOARDED = 'ONBOARDED',
  DROPPED = 'DROPPED',
}
